### ISSUE TITLE
Out of place object

### ISSUE THREAD

**Issue by StormRider1224** [GalaxySynth/Krosis#1]
Entered dungeon and uh well its a big block in the door so..

Kinda just be there lmao
1. Go to Falkreath Tomb
2. Walk inside
BAM A whole lotta stone right in your face. do a bit of jumping to bypass it.

![The Elder Scrolls V  Skyrim Special Edition Screenshot 2020 11 16 - 18 07 18 75](https://user-images.githubusercontent.com/74585512/99353340-42fa1300-2872-11eb-9e93-91e34c9876f2.png)
![The Elder Scrolls V  Skyrim Special Edition Screenshot 2020 11 16 - 18 07 10 82](https://user-images.githubusercontent.com/74585512/99353343-455c6d00-2872-11eb-9d21-94cebc2ad925.png)

1.0.1

No additional mods were present at the time of this bug.

p.s. fucking love your list you've done a fantastic job

**Comment by GalaxySynth** [comment]
Oh dear, that's a bad one. Thanks for the report!

**Comment by GalaxySynth** [comment]
Fixed, closing issue, thank you
![ScreenShot147](https://user-images.githubusercontent.com/73800917/100065775-d21aa400-2df9-11eb-83bc-f8cea3b0e5a6.png)
